/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard.index'
import { Route as ApiPublicSchoolContactRouteImport } from './routes/api.public.school-contact'
import { Route as ApiDbTableRouteImport } from './routes/api.db.$table'
import { Route as ApiAuthSignupRouteImport } from './routes/api.auth.signup'
import { Route as ApiAuthSignoutRouteImport } from './routes/api.auth.signout'
import { Route as ApiAuthSigninRouteImport } from './routes/api.auth.signin'
import { Route as ApiAuthMeRouteImport } from './routes/api.auth.me'
import { Route as ApiAuthChangePasswordRouteImport } from './routes/api.auth.change-password'
import { Route as ApiAdminResetPasswordRouteImport } from './routes/api.admin.reset-password'
import { Route as AuthenticatedDashboardTeachersRouteImport } from './routes/_authenticated/dashboard.teachers'
import { Route as AuthenticatedDashboardStudentsRouteImport } from './routes/_authenticated/dashboard.students'
import { Route as AuthenticatedDashboardSmsRouteImport } from './routes/_authenticated/dashboard.sms'
import { Route as AuthenticatedDashboardSettingsRouteImport } from './routes/_authenticated/dashboard.settings'
import { Route as AuthenticatedDashboardSalaryRouteImport } from './routes/_authenticated/dashboard.salary'
import { Route as AuthenticatedDashboardPaymentsRouteImport } from './routes/_authenticated/dashboard.payments'
import { Route as AuthenticatedDashboardMyChildrenRouteImport } from './routes/_authenticated/dashboard.my-children'
import { Route as AuthenticatedDashboardMarksRouteImport } from './routes/_authenticated/dashboard.marks'
import { Route as AuthenticatedDashboardClassesRouteImport } from './routes/_authenticated/dashboard.classes'
import { Route as AuthenticatedDashboardAttendanceRouteImport } from './routes/_authenticated/dashboard.attendance'
import { Route as ApiDbTableIdRouteImport } from './routes/api.db.$table.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const ApiPublicSchoolContactRoute = ApiPublicSchoolContactRouteImport.update({
  id: '/api/public/school-contact',
  path: '/api/public/school-contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDbTableRoute = ApiDbTableRouteImport.update({
  id: '/api/db/$table',
  path: '/api/db/$table',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSignupRoute = ApiAuthSignupRouteImport.update({
  id: '/api/auth/signup',
  path: '/api/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSignoutRoute = ApiAuthSignoutRouteImport.update({
  id: '/api/auth/signout',
  path: '/api/auth/signout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSigninRoute = ApiAuthSigninRouteImport.update({
  id: '/api/auth/signin',
  path: '/api/auth/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthMeRoute = ApiAuthMeRouteImport.update({
  id: '/api/auth/me',
  path: '/api/auth/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthChangePasswordRoute = ApiAuthChangePasswordRouteImport.update({
  id: '/api/auth/change-password',
  path: '/api/auth/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminResetPasswordRoute = ApiAdminResetPasswordRouteImport.update({
  id: '/api/admin/reset-password',
  path: '/api/admin/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardTeachersRoute =
  AuthenticatedDashboardTeachersRouteImport.update({
    id: '/teachers',
    path: '/teachers',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardStudentsRoute =
  AuthenticatedDashboardStudentsRouteImport.update({
    id: '/students',
    path: '/students',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardSmsRoute =
  AuthenticatedDashboardSmsRouteImport.update({
    id: '/sms',
    path: '/sms',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardSettingsRoute =
  AuthenticatedDashboardSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardSalaryRoute =
  AuthenticatedDashboardSalaryRouteImport.update({
    id: '/salary',
    path: '/salary',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardPaymentsRoute =
  AuthenticatedDashboardPaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardMyChildrenRoute =
  AuthenticatedDashboardMyChildrenRouteImport.update({
    id: '/my-children',
    path: '/my-children',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardMarksRoute =
  AuthenticatedDashboardMarksRouteImport.update({
    id: '/marks',
    path: '/marks',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardClassesRoute =
  AuthenticatedDashboardClassesRouteImport.update({
    id: '/classes',
    path: '/classes',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAttendanceRoute =
  AuthenticatedDashboardAttendanceRouteImport.update({
    id: '/attendance',
    path: '/attendance',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const ApiDbTableIdRoute = ApiDbTableIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiDbTableRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/dashboard/attendance': typeof AuthenticatedDashboardAttendanceRoute
  '/dashboard/classes': typeof AuthenticatedDashboardClassesRoute
  '/dashboard/marks': typeof AuthenticatedDashboardMarksRoute
  '/dashboard/my-children': typeof AuthenticatedDashboardMyChildrenRoute
  '/dashboard/payments': typeof AuthenticatedDashboardPaymentsRoute
  '/dashboard/salary': typeof AuthenticatedDashboardSalaryRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/dashboard/sms': typeof AuthenticatedDashboardSmsRoute
  '/dashboard/students': typeof AuthenticatedDashboardStudentsRoute
  '/dashboard/teachers': typeof AuthenticatedDashboardTeachersRoute
  '/api/admin/reset-password': typeof ApiAdminResetPasswordRoute
  '/api/auth/change-password': typeof ApiAuthChangePasswordRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/signin': typeof ApiAuthSigninRoute
  '/api/auth/signout': typeof ApiAuthSignoutRoute
  '/api/auth/signup': typeof ApiAuthSignupRoute
  '/api/db/$table': typeof ApiDbTableRouteWithChildren
  '/api/public/school-contact': typeof ApiPublicSchoolContactRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/api/db/$table/$id': typeof ApiDbTableIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard/attendance': typeof AuthenticatedDashboardAttendanceRoute
  '/dashboard/classes': typeof AuthenticatedDashboardClassesRoute
  '/dashboard/marks': typeof AuthenticatedDashboardMarksRoute
  '/dashboard/my-children': typeof AuthenticatedDashboardMyChildrenRoute
  '/dashboard/payments': typeof AuthenticatedDashboardPaymentsRoute
  '/dashboard/salary': typeof AuthenticatedDashboardSalaryRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/dashboard/sms': typeof AuthenticatedDashboardSmsRoute
  '/dashboard/students': typeof AuthenticatedDashboardStudentsRoute
  '/dashboard/teachers': typeof AuthenticatedDashboardTeachersRoute
  '/api/admin/reset-password': typeof ApiAdminResetPasswordRoute
  '/api/auth/change-password': typeof ApiAuthChangePasswordRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/signin': typeof ApiAuthSigninRoute
  '/api/auth/signout': typeof ApiAuthSignoutRoute
  '/api/auth/signup': typeof ApiAuthSignupRoute
  '/api/db/$table': typeof ApiDbTableRouteWithChildren
  '/api/public/school-contact': typeof ApiPublicSchoolContactRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/api/db/$table/$id': typeof ApiDbTableIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/_authenticated/dashboard/attendance': typeof AuthenticatedDashboardAttendanceRoute
  '/_authenticated/dashboard/classes': typeof AuthenticatedDashboardClassesRoute
  '/_authenticated/dashboard/marks': typeof AuthenticatedDashboardMarksRoute
  '/_authenticated/dashboard/my-children': typeof AuthenticatedDashboardMyChildrenRoute
  '/_authenticated/dashboard/payments': typeof AuthenticatedDashboardPaymentsRoute
  '/_authenticated/dashboard/salary': typeof AuthenticatedDashboardSalaryRoute
  '/_authenticated/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/_authenticated/dashboard/sms': typeof AuthenticatedDashboardSmsRoute
  '/_authenticated/dashboard/students': typeof AuthenticatedDashboardStudentsRoute
  '/_authenticated/dashboard/teachers': typeof AuthenticatedDashboardTeachersRoute
  '/api/admin/reset-password': typeof ApiAdminResetPasswordRoute
  '/api/auth/change-password': typeof ApiAuthChangePasswordRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/signin': typeof ApiAuthSigninRoute
  '/api/auth/signout': typeof ApiAuthSignoutRoute
  '/api/auth/signup': typeof ApiAuthSignupRoute
  '/api/db/$table': typeof ApiDbTableRouteWithChildren
  '/api/public/school-contact': typeof ApiPublicSchoolContactRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/api/db/$table/$id': typeof ApiDbTableIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/dashboard'
    | '/dashboard/attendance'
    | '/dashboard/classes'
    | '/dashboard/marks'
    | '/dashboard/my-children'
    | '/dashboard/payments'
    | '/dashboard/salary'
    | '/dashboard/settings'
    | '/dashboard/sms'
    | '/dashboard/students'
    | '/dashboard/teachers'
    | '/api/admin/reset-password'
    | '/api/auth/change-password'
    | '/api/auth/me'
    | '/api/auth/signin'
    | '/api/auth/signout'
    | '/api/auth/signup'
    | '/api/db/$table'
    | '/api/public/school-contact'
    | '/dashboard/'
    | '/api/db/$table/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/dashboard/attendance'
    | '/dashboard/classes'
    | '/dashboard/marks'
    | '/dashboard/my-children'
    | '/dashboard/payments'
    | '/dashboard/salary'
    | '/dashboard/settings'
    | '/dashboard/sms'
    | '/dashboard/students'
    | '/dashboard/teachers'
    | '/api/admin/reset-password'
    | '/api/auth/change-password'
    | '/api/auth/me'
    | '/api/auth/signin'
    | '/api/auth/signout'
    | '/api/auth/signup'
    | '/api/db/$table'
    | '/api/public/school-contact'
    | '/dashboard'
    | '/api/db/$table/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/sitemap.xml'
    | '/_authenticated/dashboard'
    | '/_authenticated/dashboard/attendance'
    | '/_authenticated/dashboard/classes'
    | '/_authenticated/dashboard/marks'
    | '/_authenticated/dashboard/my-children'
    | '/_authenticated/dashboard/payments'
    | '/_authenticated/dashboard/salary'
    | '/_authenticated/dashboard/settings'
    | '/_authenticated/dashboard/sms'
    | '/_authenticated/dashboard/students'
    | '/_authenticated/dashboard/teachers'
    | '/api/admin/reset-password'
    | '/api/auth/change-password'
    | '/api/auth/me'
    | '/api/auth/signin'
    | '/api/auth/signout'
    | '/api/auth/signup'
    | '/api/db/$table'
    | '/api/public/school-contact'
    | '/_authenticated/dashboard/'
    | '/api/db/$table/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiAdminResetPasswordRoute: typeof ApiAdminResetPasswordRoute
  ApiAuthChangePasswordRoute: typeof ApiAuthChangePasswordRoute
  ApiAuthMeRoute: typeof ApiAuthMeRoute
  ApiAuthSigninRoute: typeof ApiAuthSigninRoute
  ApiAuthSignoutRoute: typeof ApiAuthSignoutRoute
  ApiAuthSignupRoute: typeof ApiAuthSignupRoute
  ApiDbTableRoute: typeof ApiDbTableRouteWithChildren
  ApiPublicSchoolContactRoute: typeof ApiPublicSchoolContactRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/api/public/school-contact': {
      id: '/api/public/school-contact'
      path: '/api/public/school-contact'
      fullPath: '/api/public/school-contact'
      preLoaderRoute: typeof ApiPublicSchoolContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/db/$table': {
      id: '/api/db/$table'
      path: '/api/db/$table'
      fullPath: '/api/db/$table'
      preLoaderRoute: typeof ApiDbTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/signup': {
      id: '/api/auth/signup'
      path: '/api/auth/signup'
      fullPath: '/api/auth/signup'
      preLoaderRoute: typeof ApiAuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/signout': {
      id: '/api/auth/signout'
      path: '/api/auth/signout'
      fullPath: '/api/auth/signout'
      preLoaderRoute: typeof ApiAuthSignoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/signin': {
      id: '/api/auth/signin'
      path: '/api/auth/signin'
      fullPath: '/api/auth/signin'
      preLoaderRoute: typeof ApiAuthSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/me': {
      id: '/api/auth/me'
      path: '/api/auth/me'
      fullPath: '/api/auth/me'
      preLoaderRoute: typeof ApiAuthMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/change-password': {
      id: '/api/auth/change-password'
      path: '/api/auth/change-password'
      fullPath: '/api/auth/change-password'
      preLoaderRoute: typeof ApiAuthChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/reset-password': {
      id: '/api/admin/reset-password'
      path: '/api/admin/reset-password'
      fullPath: '/api/admin/reset-password'
      preLoaderRoute: typeof ApiAdminResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard/teachers': {
      id: '/_authenticated/dashboard/teachers'
      path: '/teachers'
      fullPath: '/dashboard/teachers'
      preLoaderRoute: typeof AuthenticatedDashboardTeachersRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/students': {
      id: '/_authenticated/dashboard/students'
      path: '/students'
      fullPath: '/dashboard/students'
      preLoaderRoute: typeof AuthenticatedDashboardStudentsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/sms': {
      id: '/_authenticated/dashboard/sms'
      path: '/sms'
      fullPath: '/dashboard/sms'
      preLoaderRoute: typeof AuthenticatedDashboardSmsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/settings': {
      id: '/_authenticated/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof AuthenticatedDashboardSettingsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/salary': {
      id: '/_authenticated/dashboard/salary'
      path: '/salary'
      fullPath: '/dashboard/salary'
      preLoaderRoute: typeof AuthenticatedDashboardSalaryRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/payments': {
      id: '/_authenticated/dashboard/payments'
      path: '/payments'
      fullPath: '/dashboard/payments'
      preLoaderRoute: typeof AuthenticatedDashboardPaymentsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/my-children': {
      id: '/_authenticated/dashboard/my-children'
      path: '/my-children'
      fullPath: '/dashboard/my-children'
      preLoaderRoute: typeof AuthenticatedDashboardMyChildrenRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/marks': {
      id: '/_authenticated/dashboard/marks'
      path: '/marks'
      fullPath: '/dashboard/marks'
      preLoaderRoute: typeof AuthenticatedDashboardMarksRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/classes': {
      id: '/_authenticated/dashboard/classes'
      path: '/classes'
      fullPath: '/dashboard/classes'
      preLoaderRoute: typeof AuthenticatedDashboardClassesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/attendance': {
      id: '/_authenticated/dashboard/attendance'
      path: '/attendance'
      fullPath: '/dashboard/attendance'
      preLoaderRoute: typeof AuthenticatedDashboardAttendanceRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/api/db/$table/$id': {
      id: '/api/db/$table/$id'
      path: '/$id'
      fullPath: '/api/db/$table/$id'
      preLoaderRoute: typeof ApiDbTableIdRouteImport
      parentRoute: typeof ApiDbTableRoute
    }
  }
}

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardAttendanceRoute: typeof AuthenticatedDashboardAttendanceRoute
  AuthenticatedDashboardClassesRoute: typeof AuthenticatedDashboardClassesRoute
  AuthenticatedDashboardMarksRoute: typeof AuthenticatedDashboardMarksRoute
  AuthenticatedDashboardMyChildrenRoute: typeof AuthenticatedDashboardMyChildrenRoute
  AuthenticatedDashboardPaymentsRoute: typeof AuthenticatedDashboardPaymentsRoute
  AuthenticatedDashboardSalaryRoute: typeof AuthenticatedDashboardSalaryRoute
  AuthenticatedDashboardSettingsRoute: typeof AuthenticatedDashboardSettingsRoute
  AuthenticatedDashboardSmsRoute: typeof AuthenticatedDashboardSmsRoute
  AuthenticatedDashboardStudentsRoute: typeof AuthenticatedDashboardStudentsRoute
  AuthenticatedDashboardTeachersRoute: typeof AuthenticatedDashboardTeachersRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardAttendanceRoute:
      AuthenticatedDashboardAttendanceRoute,
    AuthenticatedDashboardClassesRoute: AuthenticatedDashboardClassesRoute,
    AuthenticatedDashboardMarksRoute: AuthenticatedDashboardMarksRoute,
    AuthenticatedDashboardMyChildrenRoute:
      AuthenticatedDashboardMyChildrenRoute,
    AuthenticatedDashboardPaymentsRoute: AuthenticatedDashboardPaymentsRoute,
    AuthenticatedDashboardSalaryRoute: AuthenticatedDashboardSalaryRoute,
    AuthenticatedDashboardSettingsRoute: AuthenticatedDashboardSettingsRoute,
    AuthenticatedDashboardSmsRoute: AuthenticatedDashboardSmsRoute,
    AuthenticatedDashboardStudentsRoute: AuthenticatedDashboardStudentsRoute,
    AuthenticatedDashboardTeachersRoute: AuthenticatedDashboardTeachersRoute,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ApiDbTableRouteChildren {
  ApiDbTableIdRoute: typeof ApiDbTableIdRoute
}

const ApiDbTableRouteChildren: ApiDbTableRouteChildren = {
  ApiDbTableIdRoute: ApiDbTableIdRoute,
}

const ApiDbTableRouteWithChildren = ApiDbTableRoute._addFileChildren(
  ApiDbTableRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiAdminResetPasswordRoute: ApiAdminResetPasswordRoute,
  ApiAuthChangePasswordRoute: ApiAuthChangePasswordRoute,
  ApiAuthMeRoute: ApiAuthMeRoute,
  ApiAuthSigninRoute: ApiAuthSigninRoute,
  ApiAuthSignoutRoute: ApiAuthSignoutRoute,
  ApiAuthSignupRoute: ApiAuthSignupRoute,
  ApiDbTableRoute: ApiDbTableRouteWithChildren,
  ApiPublicSchoolContactRoute: ApiPublicSchoolContactRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
